# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['run', '--privileged', 'linuxkit/binfmt:v0.8']
      id: 'initialize-qemu'
    - name: 'gcr.io/cloud-builders/docker:20.10.14'
      args: ['buildx', 'create', '--name', 'builder']
      id: 'create-builder'
    - name: 'gcr.io/cloud-builders/docker:20.10.14'
      args: ['buildx', 'use', 'builder']
      id: 'select-builder'
#    - name: 'gcr.io/cloud-builders/docker:20.10.14'
#      args: ['buildx', 'inspect', '--bootstrap']
#      id: 'show-target-build-platforms'
    - name: 'gcr.io/cloud-builders/docker:20.10.14'
      args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'us-docker.pkg.dev/$PROJECT_ID/envspitter/envspitter:$TAG_NAME', '--push', '.']
      id: 'build-and-push'
options:
    env:
        - 'DOCKER_CLI_EXPERIMENTAL=enabled'
substitutions:
    _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/aarch64'
...
