apiVersion: v1
kind: Service
metadata:
  name: envspitter
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: LoadBalancer 
  selector:
    app: envspitter
  sessionAffinity: None
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 80
