apiVersion: v1
kind: Service
metadata:
  name: envspitter
spec:
  type: LoadBalancer 
  selector:
    app: envspitter
  ports:
  - name: my-service-port
    protocol: TCP
    port: 80
    targetPort: 80
