apiVersion: apps/v1
kind: Deployment
metadata:
  name: envspitter
spec:
  selector:
    matchLabels:
      app: envspitter
  replicas: 6
  template:
    metadata:
      labels:
        app: envspitter
    spec:
      containers:
      - name: envspitter
        image: us-docker.pkg.dev/${PROJECT_ID}/envspitter-${USER}/envspitter:1.0
        env:
        - name: PORT
          value: "80"
        - name: MESSAGE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: "50Mi"
            cpu: "1.5"
          requests:
            memory: "50Mi"
            cpu: "1.5"
